name: 🏷️ Update Metadata

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: ⚙️ Generate Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: fregante/setup-git-user@v2
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Generate Metadata
        run: |
          pdm install
          pdm run meta update
      - name: Push Changes
        run: git push
