name: 📦️ Release Modules

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  meta:
    name: 🏷️ Update Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: fregante/setup-git-user@v2
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Generate Metadata
        run: |
          pdm install
          pdm run meta update
      - name: Push Changes
        run: git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  version:
    name: 🔍 Check Version
    needs: meta
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      release_tag: ${{ steps.definitions.outputs.release_tag }}
      release_name: ${{ steps.definitions.outputs.release_name }}
    steps:
      - name: Check Versions
        id: definitions
        run: |
          VERSION=$(python core/definitions.py VERSION)
          MINECRAFT_VERSIONS=$(python core/definitions.py MINECRAFT_VERSIONS)
          name=$(echo $MINECRAFT_VERSIONS | sed 's/ /,/g')
          echo "release_tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "release_name=v$VERSION - MC $name" >> $GITHUB_OUTPUT
  release:
    name: 🔖 Create Release
    needs: version
    runs-on: ubuntu-latest
    if: ${{ needs.version.outputs.release_tag != '' }}
    steps:
      - uses: fregante/setup-git-user@v2
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Build Release Files
        run: |
          pdm install
          pdm run modules release
      - uses: softprops/action-gh-release@v2
        with:
          body_path: docs/_templates/changelog/${{ needs.version.outputs.release_tag }}.md
          name: ${{ needs.version.outputs.release_name }}
          tag_name: ${{ needs.version.outputs.release_tag }}
          make_latest: true
          files: release/*.zip
