name: 📋 Review Modules

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: 🔍 Check Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Check Modules
        run: |
          pdm install
          pdm run modules check
  test:
    name: 🧪 Test Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test Modules
        run: |
          pdm install
          pdm run modules test
